{
 "title": "Kubernetes Metrics - Deployments vs StatefulSets vs DaemonSets",
 "description": "To monitors kubernetes (version 1.16 or above) deployments in cluster using Prometheus.",
 "tags": [
  "kubernetes",
  "deployment",
  "statefulset",
  "daemonset"
 ],
 "time": { "from": "now-45m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Deployment", "query": { "query": "label_values(deployment)" } },
   { "name": "Statefulset", "query": { "query": "label_values(statefulset)" } },
   { "name": "Daemonset", "query": { "query": "label_values(daemonset)" } },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Deployment$Statefulset$Daemonset.*$\", kubernetes_io_hostname=~\"^$Node$\", pod!=\"\"}) / sum (kube_node_status_allocatable{resource=\"memory\",node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Deployment$Statefulset$Daemonset.*$\", kubernetes_io_hostname=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))) - ((sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)))) / ((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Deployment$Statefulset$Daemonset.*$\", kubernetes_io_hostname=~\"^$Node$\", pod!=\"\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable{resource=\"memory\",node=~\"^$Node.*$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Deployment$Statefulset$Daemonset.*$\", kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))",
     "legendFormat": "{{ $Daemonset }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod,kubernetes_io_hostname)",
     "legendFormat": "real: {{ kubernetes_io_hostname }} | {{ pod }} "
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{pod=~\"^$Deployment$Statefulset$Daemonset.*$\",node=~\"^$Node$\"}) by (pod,node)",
     "legendFormat": "rqst: {{ node }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod,kubernetes_io_hostname)",
     "legendFormat": "real: {{kubernetes_io_hostname }} | {{ pod }}"
    },
    {
     "expr": "sum ((kube_pod_container_resource_requests_memory_bytes{pod=~\"^$Deployment$Statefulset$Daemonset.*$\",node=~\"^$Node$\"})) by (pod,node)",
     "legendFormat": "rqst: {{ node }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (kubelet_volume_stats_used_bytes{kubernetes_io_hostname=~\"^$Node$\", persistentvolumeclaim=~\".*$Deployment$Statefulset$Daemonset.*$\"} / kubelet_volume_stats_capacity_bytes{kubernetes_io_hostname=~\"^$Node$\", persistentvolumeclaim=~\".*$Deployment$Statefulset$Daemonset.*$\"})",
     "legendFormat": "{{ persistentvolumeclaim }} | {{ kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod, kubernetes_io_hostname)",
     "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{id!=\"/\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod, kubernetes_io_hostname)",
     "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "Pod Stats & Info",
 "description": "This is for insight on important Kubernetes app metrics.\r\nWhat recources is a Pod actually using and what are it's limits or requests and what part is each container consuming?\r\nAlso has graphs for networking, disks, restarts docker images etc",
 "tags": [
  "kubernetes",
  "pod"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\",pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU: $pod",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\"}[1m]))",
     "legendFormat": "CPU: $pod"
    }
   ]
  },
  {
   "title": "CPU: $container",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "repeat": "container",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",container!=\"POD\",pod=\"$pod\",container=\"$container\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",container!=\"POD\",pod=\"$pod\",container=\"$container\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\",container=\"$container\"}[1m])) by (container)",
     "legendFormat": "Usage: {{ container }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory: $pod",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\"})",
     "legendFormat": "MEM"
    },
    {}
   ]
  },
  {
   "title": "Memory: $container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "repeat": "container",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\",container=\"$container\"}) by (container)",
     "legendFormat": "Usage: {{ container }}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Disk Usage: $container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "repeat": "container",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\"}[1m])) by (container,device)",
     "legendFormat": "Read {{ device }}"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\"}[1m])) by (container,device)",
     "legendFormat": "Write {{ device }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Network: $pod",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[5m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[5m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Network-Errors: $pod",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_receive_errors_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Receive-Errors%"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Receive-Dropped%"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_transmit_errors_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Transmit-Errors%"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Transmit-Dropped%"
    }
   ]
  },
  { "title": "Restarts & Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Ready: $container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "repeat": "container",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Restarts: $container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "repeat": "container",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=\"$pod\", container=\"$container\"}[1m])",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\", pod=\"$pod\"} > 0"
    }
   ]
  },
  {
   "title": "Waiting Reason",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\", pod=\"$pod\"} > 0"
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Pod created",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_created{namespace=\"$namespace\",pod=\"$pod\"} * 1000",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "Info: $pod",
   "type": "table-old",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  }
 ]
}